export const PagesLinks = {
  MAIN_PAGE: '/',
  NEWS_PAGE: '/news',
  RATES_PAGE: '/rates',
  MAPS_PAGE: '/maps',
  CONTACTS_PAGE: '/contacts',
  BOOKMARKS_PAGE: '/bookmarks',
  APARTMENTS_PAGE: '/apartments',
  APARTMENTS_MINSK_PAGE: '/apartments/minsk',
  APARTMENTS_GOMEL_PAGE: '/apartments/gomel',
  APARTMENTS_BREST_PAGE: '/apartments/brest',
  APARTMENTS_VITEBSK_PAGE: '/apartments/vitebsk',
  APARTMENTS_GRODNO_PAGE: '/apartments/grodno',
  APARTMENTS_MOGILEV_PAGE: '/apartments/mogilev',
  COTTAGES_PAGE: '/cottages',
  SAUNAS_PAGE: '/saunas',
  AUTO_PAGE: '/auto',
  ADMIN_PAGE: '/admin',
  LOGIN_PAGE: '/login',
  REG_PAGE: '/registration',
};
